language: node_js

node_js: 
  - 10.13.0

install:
  - npm install

script:
  - npm test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_KEY
  secret_access_key:
    secure: $AWS_SECRET
  region: "ap-southeast-1"
  app: "sample-deploy"
  env: "SampleDeploy-env"

# deploy:
#   provider: heroku
#   skip-cleanup: true
#   app: sample-deploy-1
#   api_key: 
#       secure: $HEROKU_API_KEY
#   on:
#     branch: master
